#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

#
PATH="$PATH:/opt/homebrew/bin"
PATH="$PATH:$HOME/.local/bin"

function error() {
  local red="\033[31m"
  local reset="\033[0m"
  local prefix="[ERROR] "
  local message=$1
  echo -e "${red}${prefix}${message}${reset}"
}

function success() {
  local green="\033[32m"
  local reset="\033[0m"
  local prefix="[SUCCESS] "
  local message=$1
  echo -e "${green}${prefix}${message}${reset}"
}

function warning() {
  local yellow="\033[33m"
  local reset="\033[0m"
  local prefix="[WARNING] "
  local message=$1
}

function info() {
  local cyan="\033[36m"
  local reset="\033[0m"
  local prefix="[INFO] "
  local message=$1
  echo -e "${cyan}${prefix}${message}${reset}"
}

# Install fish
{
  info "Checking Fish..."

  #
  if ! which fish >/dev/null 2>&1; then
    warning "Fish is not installed"
    info "Installing Fish..."
    pacman -S fish
    success "Fish installed successfully"
  else
    info "Fish is already installed"
  fi
}

# Install fisher
{
  info "Checking Fisher..."

  if ! which fisher >/dev/null 2>&1; then
    warning "Fisher is not installed"
    info "Installing Fisher..."
    curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
    fisher install jorgebucaran/fisher
    success "Fisher installed successfully"
  else
    info "Fisher is already installed"
  fi
}
