#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

function error() {
  local red="\033[31m"
  local reset="\033[0m"
  local prefix="[ERROR] "
  local message=$1
  echo -e "${red}${prefix}${message}${reset}"
}

function success() {
  local green="\033[32m"
  local reset="\033[0m"
  local prefix="[SUCCESS] "
  local message=$1
  echo -e "${green}${prefix}${message}${reset}"
}

function warning() {
  local yellow="\033[33m"
  local reset="\033[0m"
  local prefix="[WARNING] "
  local message=$1
}

function info() {
  local cyan="\033[36m"
  local reset="\033[0m"
  local prefix="[INFO] "
  local message=$1
  echo -e "${cyan}${prefix}${message}${reset}"
}

function symlink() {

  # Create parent directory if it doesn't exist
  local target_dir
  target_dir=$(dirname "$2")
  mkdir -p "$target_dir"

  # Remove existing file or symlink
  if [ -e "$2" ] || [ -L "$2" ]; then
    rm -rf "$2"
    info "Removed existing file/symlink: $2"
  fi

  # Create symlink
  ln -nfs "$1" "$2"

  #
  success "Symlink created: $2 -> $1"
}

# Link configuration files
{
  info "Linking configuration files..."

  ## bashrc
  symlink "$PWD/config/bash/.bashrc" "$HOME/.bashrc"

  ## git
  symlink "$PWD/config/git/.gitconfig" "$HOME/.gitconfig"

  ## ssh
  symlink "$PWD/config/ssh/config" "$HOME/.ssh/config"

  ## homebrew
  symlink "$PWD/config/homebrew/.Brewfile" "$HOME/.Brewfile"

  ## fish
  mkdir -p  "$HOME/.config/fish"
  symlink "$PWD/config/fish/config.fish" "$HOME/.config/fish/config.fish"
  symlink "$PWD/config/fish/fish_plugins" "$HOME/.config/fish/fish_plugins"
  symlink "$PWD/config/fish/functions/fish_greeting.fish" "$HOME/.config/fish/functions/fish_greeting.fish"
  # symlink "$PWD/config/fish/fish_variables" "$HOME/.config/fish/fish_variables"
  # symlink "$PWD/config/fish/completions" "$HOME/.config/fish/completions"
  # symlink "$PWD/config/fish/conf.d" "$HOME/.config/fish/conf.d"
  # symlink "$PWD/config/fish/functions" "$HOME/.config/fish/functions"

  ## fisher plugins
  symlink "$PWD/config/fish/fish_plugins" "$HOME/.config/fish/fish_plugins"

  ## mise
  mkdir -p  "$HOME/.config/mise"
  symlink "$PWD/config/mise" "$HOME/.config/mise"

  ## ghostty
  symlink "$PWD/config/ghostty" "$HOME/.config/ghostty"

  #
  info "Linking completed"
}
