#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

function error() {
  local red="\033[31m"
  local reset="\033[0m"
  local prefix="[ERROR] "ee
  local message=$1
  echo -e "${red}${prefix}${message}${reset}"
}

function success() {
  local green="\033[32m"
  local reset="\033[0m"
  local prefix="[SUCCESS] "
  local message=$1
  echo -e "${green}${prefix}${message}${reset}"
}

function warning() {
  local yellow="\033[33m"
  local reset="\033[0m"
  local prefix="[WARNING] "
  local message=$1
}

function info() {
  local cyan="\033[36m"
  local reset="\033[0m"
  local prefix="[INFO] "
  local message=$1
  echo -e "${cyan}${prefix}${message}${reset}"
}

function symlink() {
  # Windows does not support symlinking
  error "Symlinking is not supported on Windows"
}

error "This script is not supported on Windows"
exit 1
