name: validate

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        run: |
          git clone "https://github.com/${GITHUB_REPOSITORY}.git" .
          git checkout "${GITHUB_SHA}"

      - name: Install chezmoi
        run: |
          sudo apt-get update
          sudo apt-get install -y chezmoi

      - name: Run validation
        run: |
          make dry-run
